# Generated by Django 2.2.19 on 2022-09-28 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20220928_2333'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ingridient',
            constraint=models.UniqueConstraint(fields=('name', 'measurement_unit'), name='unique_name_measurement_unit'),
        ),
    ]
