# Generated by Django 2.2.19 on 2022-09-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20220929_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingridient',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Название'),
        ),
    ]
